### PR TITLE
Added docker deploy job with static IPs to github workflow

### PR DESCRIPTION
**Pull request by bgentry-ntap**

### CODE REVIEW

**Comment by bgentry-ntap** [comment]
I'm not sure if this is related to the retry from the etcd failure or my changes: 
```
module.rancher.local_file.rkeconfig: Creation complete after 0s [id=6a2e8658c7a642506cc50252188806033d53cc9e]
module.rancher.helm_release.rancher: Creating...

Error: cannot re-use a name that is still in use

  on ../modules/kubernetes/rancher/main.tf line 79, in resource "helm_release" "rancher":
  79: resource "helm_release" "rancher" {
```

**Comment by sgryczan** [comment]
Seems like TF should be deleting the existing resource before attempting the re-apply after a failure, but isn't for some reason. This is the first I've seen that happen, but it doesn't seem related to your changes - I'm good with this.

**Comment by hulquest** [comment]
> Seems like TF should be deleting the existing resource before attempting the re-apply after a failure, but isn't for some reason. This is the first I've seen that happen, but it doesn't seem related to your changes - I'm good with this.

I wonder if we should run the tests serially since dhcp and static deployments are failing at about the same time.

**Comment by sgryczan** [comment]
> > Seems like TF should be deleting the existing resource before attempting the re-apply after a failure, but isn't for some reason. This is the first I've seen that happen, but it doesn't seem related to your changes - I'm good with this.
> 
> I wonder if we should run the tests serially since dhcp and static deployments are failing at about the same time.

That's definitely an option...I guess the tradeoff being longer builds.

Maybe disabling helm `wait` could help avoid instances of this occurring?

**Comment by bgentry-ntap** [comment]
It seems like the helm object in terraform is not recognizing it's state correctly and trying to re-add the helm repos on the retry

**Comment by bgentry-ntap** [comment]
New error 🤦 
```
module.rancher.helm_release.rancher: Creating...

Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: x509: certificate signed by unknown authority

  on ../modules/kubernetes/rancher/main.tf line 80, in resource "helm_release" "rancher":
  80: resource "helm_release" "rancher" {

```

**Comment by bgentry-ntap** [comment]
> New error 🤦
> 
> ```
> module.rancher.helm_release.rancher: Creating...
> 
> Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: x509: certificate signed by unknown authority
> 
>   on ../modules/kubernetes/rancher/main.tf line 80, in resource "helm_release" "rancher":
>   80: resource "helm_release" "rancher" {
> ```

Hmm, appears to be intermittent. I don't even know if this is re-tryable, @sgryczan thoughts on adding this to the list and seeing if we can reproduce this?

**Comment by sgryczan** [comment]
I'm not sure if it is either. I opened a branch for testing that [here](https://github.com/NetApp/ez-rancher/tree/retry_cert_mgr)

**Pull request merged**
