### PR TITLE
Pin all package versions

### PR DESCRIPTION
**Pull request by bgentry-ntap**

### CODE REVIEW

**Comment by bgentry-ntap** [comment]
This definitely locks us into a specific distro, not sure if we actually want that or not

**Review by jacobweinstock — APPROVED** [review]
LGTM. might want to think about locking down the version of ubuntu now too

**Review by hulquest — APPROVED** [review]
This looks good to me and relieves the immediate pressure.  I'd like to talk about a strategy of pinning for releases and letting main float.  We'll get burned by tightly pinning dependencies with the same frequency as just letting them float.

**Comment by bgentry-ntap** [comment]
vmware cloud-init, docker, rke, and rancher versions pinned on release branch: https://github.com/NetApp/ez-rancher/tree/release/bryce-canyon

**Pull request closed without merging**
